export const LOGIN_ROUTE = '/movies_app/*'
export const CONTENT_ROUTE = '/movies_app/'
export const CONTENT_DETAILS_ROUTE = '/movies_app/details'
export const QUIZ_ROUTE = '/movies_app/quiz'
export const HOME_ROUTE = 'movies_app/home'